name: CI/CD

# Um Push na branch main
on:
  push:
    branches:
      - master

jobs:
  CI: #Inicializa JOB
    name: Continuous Integration
    runs-on: ubuntu-latest #Imagem da maquina que vai rodar o Job

    steps: #Passos do JOB
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #  run: npm test

  CD:
    name: Continuos Delivery
    runs-on: ubuntu-latest

    needs: CI #Precisa esperar o job do CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Setupe EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Get config file #Converte o b64 salvo no secrets para um JSON
        env: 
           GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
        run: | 
          echo $GOOGLE_SERVICES_64 > google-services.json.b64
          base64 -d -i google-services.json.b64 > google-services.json

      - name: Build and submit
        run: eas build --platform android --profile production --non-interactive --auto-submit-with-profile=preview --no-wait